# version: '3.8'
services:
  # postgres:
  #   image: postgres:13
  #   container_name: postgresdb
  #   environment:
  #     - POSTGRES_USER=airflow
  #     - POSTGRES_PASSWORD=airflow
  #     - POSTGRES_DB=airflow
  #   ports:
  #     - "127.0.0.1:5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - airflow-net

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - airflow-net

networks:
  airflow-net:
    driver: bridge

volumes:
  postgres_data:
  mongo_data: